"use client";

import { useMemo, useState } from "react";

type Tier = "large" | "medium" | "small";
type CategoryRule = { packQty:number; single:number; carton:number; tenCartons:number };
type Customer = { username: string; password: string; name: string; tier: Tier; address: string };
type Variant = { id:string; label:string; labelZh:string; base:number };
type Product = { id:number; code:string; category:string; categoryZh:string; categoryEn:string; name:string; zh:string; spec:string; pack:string; packZh:string; packQty:number; variants:Variant[]; image:string };
type TierPolicy = Record<Tier,{allBest:boolean;bestCategories:string[]}>;

const tierInfo:Record<Tier,{vi:string;zh:string;code:string}> = {
  large:{vi:"Đại lý lớn",zh:"大盤客戶",code:"ĐẠI BÀN"},
  medium:{vi:"Đại lý vừa",zh:"中盤客戶",code:"TRUNG BÀN"},
  small:{vi:"Cửa hàng bán lẻ",zh:"小盤客戶",code:"TIỂU BÀN"},
};
const initialCustomers:Customer[] = [
  {username:"minhphat",password:"123456",name:"VLXD Minh Phát",tier:"large",address:"128 Nguyễn Văn Linh, Q.7, TP.HCM"},
  {username:"anphu",password:"123456",name:"Điện Nước An Phú",tier:"medium",address:"42 Lê Văn Việt, TP. Thủ Đức"},
  {username:"hoangnam",password:"123456",name:"Cửa hàng Hoàng Nam",tier:"small",address:"19 QL1A, Bình Tân, TP.HCM"},
];
const initialCategoryRules:Record<string,CategoryRule> = {
  "FLEXIBLE HOSE":{packQty:100,single:100,carton:90,tenCartons:80},
  "SHOWER":{packQty:50,single:100,carton:92,tenCartons:85},
  "SHATTAF":{packQty:40,single:100,carton:90,tenCartons:82},
  "WATER LEVEL CONTROL":{packQty:20,single:100,carton:88,tenCartons:78},
};
const initialTierPolicies:TierPolicy = {
  large:{allBest:true,bestCategories:[]},
  medium:{allBest:false,bestCategories:["FLEXIBLE HOSE","WATER LEVEL CONTROL"]},
  small:{allBest:false,bestCategories:[]},
};
const catalogueGroups:{en:string;vi:string;zh:string;packQty:number;items:[string,string][]}[] = [
  {en:"FLEXIBLE HOSE",vi:"Dây cấp nước",zh:"給水軟管",packQty:100,items:[
    ["102XI05","https://www.shintung-onspa.com/upload/2018/10/18/1539847068.jpg"],["102XI05","https://www.shintung-onspa.com/upload/2018/10/18/1539846019.jpg"],["102XD01","https://www.shintung-onspa.com/upload/2016/12/09/1481272647.jpg"],["102XS01","https://www.shintung-onspa.com/cache/fillw_737h_737/2cc328c791c56edaff2f700cd02b90cd1501661507.jpg.png"],["102XL01","https://www.shintung-onspa.com/upload/2016/12/09/1481261489.jpg"],["102XS03","https://www.shintung-onspa.com/upload/2016/12/09/1481264540.jpg"],["102XI02","https://www.shintung-onspa.com/upload/2016/12/09/1481262576.jpg"],["102XI01","https://www.shintung-onspa.com/cache/fillw_737h_737/952984cf71ccf086b44e5d391cfb0f901477662560.jpg.png"],["102IC01","https://www.shintung-onspa.com/upload/2016/12/09/1481266326.jpg"],["102XT04","https://www.shintung-onspa.com/cache/fillw_737h_737/c5bf50b6c9cf09a15a56a939d6596ade1735978152.png.png"],["102XT01","https://www.shintung-onspa.com/upload/2016/12/08/1481173708.jpg"],["102MG01","https://www.shintung-onspa.com/upload/2016/12/09/1481269694.jpg"],["102DG01","https://www.shintung-onspa.com/upload/2016/12/09/1481260035.jpg"]]},
  {en:"SHOWER",vi:"Vòi sen",zh:"花灑",packQty:50,items:[
    ["103S283201","https://www.shintung-onspa.com/upload/2024/09/07/1725681592.jpg"],["103S183204","https://www.shintung-onspa.com/upload/2024/09/06/1725612951.jpg"],["103S282201","https://www.shintung-onspa.com/upload/2024/09/06/1725614008.jpg"],["103S182204","https://www.shintung-onspa.com/upload/2024/09/06/1725610345.jpg"],["103SM32101","https://www.shintung-onspa.com/upload/2024/09/06/1725605053.jpg"],["103SM31101","https://www.shintung-onspa.com/upload/2024/09/06/1725596430.jpg"],["103S194121","https://www.shintung-onspa.com/upload/2024/09/06/1725594057.jpg"],["103S194111","https://www.shintung-onspa.com/upload/2024/09/06/1725592968.jpg"],["103S194101","https://www.shintung-onspa.com/upload/2024/09/06/1725590166.jpg"],["103S193101","https://www.shintung-onspa.com/upload/2025/05/09/1746782118.jpg"],["103SM00013","https://www.shintung-onspa.com/upload/2022/09/19/1663571546.jpg"],["103SM00011","https://www.shintung-onspa.com/upload/2020/11/02/1604302308.jpg"],["103SM00012","https://www.shintung-onspa.com/upload/2020/11/02/1604300335.jpg"],["103SM00004","https://www.shintung-onspa.com/upload/2017/09/07/1504758595.jpg"],["103SM00001","https://www.shintung-onspa.com/upload/2016/12/14/1481698159.jpg"],["103SM00002","https://www.shintung-onspa.com/upload/2016/12/14/1481698107.jpg"],["103SM00003","https://www.shintung-onspa.com/upload/2016/12/14/1481698042.jpg"],["103S101","https://www.shintung-onspa.com/upload/2016/12/14/1481698614.jpg"],["103S103","https://www.shintung-onspa.com/upload/2016/12/14/1481698539.jpg"],["103S110","https://www.shintung-onspa.com/upload/2016/12/14/1481698426.jpg"],["103S111","https://www.shintung-onspa.com/upload/2016/12/14/1481698363.jpg"],["103S112","https://www.shintung-onspa.com/upload/2016/12/14/1481698280.jpg"],["103S205","https://www.shintung-onspa.com/cache/fillw_737h_737/ce6b7038aedb78a230d64358560710ec1504760822.jpg.png"],["103S204","https://www.shintung-onspa.com/cache/fillw_737h_737/c2f3cd57c61df38095befca5908dcf001504760777.jpg.png"],["103S2082","https://www.shintung-onspa.com/upload/2017/09/07/1504758960.jpg"],["103S24B","https://www.shintung-onspa.com/upload/2017/09/07/1504758979.jpg"],["103S206","https://www.shintung-onspa.com/upload/2017/09/07/1504759022.jpg"],["103S209","https://www.shintung-onspa.com/upload/2017/09/07/1504759043.jpg"],["103S292","https://www.shintung-onspa.com/upload/2017/09/07/1504759138.jpg"],["103S209204","https://www.shintung-onspa.com/upload/2017/09/07/1504760212.jpg"],["103S209205","https://www.shintung-onspa.com/upload/2017/09/07/1504759914.jpg"],["103PMSX01","https://www.shintung-onspa.com/upload/2016/12/14/1481699580.jpg"],["103PMSX03","https://www.shintung-onspa.com/upload/2016/12/14/1481699542.jpg"],["102TC01","https://www.shintung-onspa.com/upload/2017/09/07/1504761839.jpg"],["102TC04","https://www.shintung-onspa.com/upload/2017/09/07/1504761857.jpg"],["102TC03","https://www.shintung-onspa.com/upload/2017/09/07/1504761868.jpg"]]},
  {en:"SHATTAF",vi:"Vòi xịt vệ sinh",zh:"沖洗器",packQty:40,items:[
    ["104A39202","https://www.shintung-onspa.com/upload/2020/10/13/1602582716.jpg"],["104A39201","https://www.shintung-onspa.com/upload/2020/10/13/1602573182.jpg"],["104A141","https://www.shintung-onspa.com/upload/2016/12/16/1481864903.jpg"],["104A4X2","https://www.shintung-onspa.com/upload/2016/12/16/1481865214.jpg"],["104A4G2","https://www.shintung-onspa.com/upload/2016/12/16/1481865357.jpg"],["104A4G1","https://www.shintung-onspa.com/upload/2016/12/16/1481865523.jpg"],["104A4X1","https://www.shintung-onspa.com/upload/2016/12/16/1481865606.jpg"],["104A3801","https://www.shintung-onspa.com/upload/2016/12/16/1481864770.jpg"],["104A33201","https://www.shintung-onspa.com/upload/2016/12/16/1481864331.jpg"],["104A32201","https://www.shintung-onspa.com/upload/2016/12/16/1481864522.jpg"],["104A4F1","https://www.shintung-onspa.com/cache/fillw_737h_737/d219eb99714a2caf95ec59fc84939eb31489650246.jpg.png"],["104A4F2","https://www.shintung-onspa.com/upload/2016/12/16/1481865286.jpg"],["104A31201","https://www.shintung-onspa.com/upload/2016/12/16/1481864710.jpg"],["104A37201","https://www.shintung-onspa.com/upload/2016/12/16/1481863941.jpg"],["104A30201","https://www.shintung-onspa.com/upload/2016/12/16/1481864833.jpg"],["104A222","https://www.shintung-onspa.com/upload/2016/12/16/1481864871.jpg"],["104A131","https://www.shintung-onspa.com/upload/2016/12/16/1481865080.jpg"],["104A132","https://www.shintung-onspa.com/upload/2016/12/16/1481865014.jpg"],["104A34201","https://www.shintung-onspa.com/upload/2016/12/16/1481863765.jpg"],["104A35201","https://www.shintung-onspa.com/cache/fillw_737h_737/4c5c6db2d77467367df9a61ab8d72d151489645898.jpg.png"],["104A101","https://www.shintung-onspa.com/upload/2016/12/16/1481865479.jpg"],["104A102","https://www.shintung-onspa.com/upload/2016/12/16/1481865115.jpg"],["104A36201","https://www.shintung-onspa.com/upload/2016/12/16/1481864080.jpg"],["104PTEX05","https://www.shintung-onspa.com/upload/2016/12/16/1481864177.jpg"],["104PTEX03","https://www.shintung-onspa.com/upload/2016/12/16/1481864214.jpg"],["104PTEX02-XI","https://www.shintung-onspa.com/upload/2016/12/16/1481864267.jpg"],["104PTEX01","https://www.shintung-onspa.com/upload/2016/12/16/1481864292.jpg"]]},
  {en:"WATER LEVEL CONTROL",vi:"Van phao bồn nước",zh:"水位控制器",packQty:20,items:[
    ["101CTP015","https://www.shintung-onspa.com/upload/2017/01/22/1485074840.jpg"],["101CTP010","https://www.shintung-onspa.com/cache/fillw_737h_737/52dd40d7128958429069aebaf513af5f1489553320.jpg.png"]]},
];
const variantLabels=(groupIndex:number):[string,string][]=>groupIndex===0
  ? [["20 cm","20公分"],["30 cm","30公分"],["40 cm","40公分"],["50 cm","50公分"]]
  : groupIndex===1
    ? [["100 cm","100公分"],["120 cm","120公分"],["150 cm","150公分"],["180 cm","180公分"]]
    : groupIndex===2
      ? [["Bộ tiêu chuẩn","標準組"],["Dây 100 cm","100公分管組"],["Dây 120 cm","120公分管組"],["Dây 150 cm","150公分管組"]]
      : [["DN15","DN15"],["DN20","DN20"],["DN25","DN25"],["DN32","DN32"]];
const initialProducts:Product[] = catalogueGroups.flatMap((group,groupIndex)=>group.items.map(([code,image],itemIndex)=>{
  const start=[32000,118000,86000,185000][groupIndex]+itemIndex*2500;
  return {
    id:groupIndex*100+itemIndex+1,code,category:group.vi,categoryZh:group.zh,categoryEn:group.en,
    name:`${group.vi} ${code}`,zh:`${group.zh} ${code}`,spec:"Dữ liệu quy cách mẫu · Chờ ERP xác nhận",
    pack:`${group.packQty} pcs / thùng`,packZh:`${group.packQty}件／箱`,packQty:group.packQty,
    variants:variantLabels(groupIndex).map(([label,labelZh],i)=>({id:`${code}-${i}`,label,labelZh,base:start+i*[4000,9000,7000,18000][groupIndex]})),image,
  };
}));
const fmt=(n:number)=>new Intl.NumberFormat("vi-VN").format(Math.round(n/100)*100)+" ₫";

export default function Home(){
  const [customers,setCustomers]=useState(initialCustomers);
  const [categoryRules,setCategoryRules]=useState(initialCategoryRules);
  const [tierPolicies,setTierPolicies]=useState(initialTierPolicies);
  const [productList,setProductList]=useState(initialProducts);
  const [user,setUser]=useState<Customer|null>(null);
  const [username,setUsername]=useState("minhphat");
  const [password,setPassword]=useState("123456");
  const [lang,setLang]=useState<"vi"|"zh">("vi");
  const [view,setView]=useState("home");
  const [admin,setAdmin]=useState(false);
  const [category,setCategory]=useState("all");
  const [search,setSearch]=useState("");
  const [qty,setQty]=useState<Record<number,number>>({});
  const [variantByProduct,setVariantByProduct]=useState<Record<number,string>>({});
  const [cart,setCart]=useState<Record<number,number>>({});
  const [selected,setSelected]=useState<Product|null>(null);
  const [toast,setToast]=useState("");
  const t=(vi:string,zh:string)=>lang==="vi"?vi:zh;
  const variant=(p:Product)=>p.variants.find(v=>v.id===variantByProduct[p.id])||p.variants[0];
  const ruleFor=(p:Product)=>categoryRules[p.categoryEn]||{packQty:p.packQty,single:100,carton:100,tenCartons:100};
  const packQtyFor=(p:Product)=>ruleFor(p).packQty;
  const quantityPercent=(n:number,p:Product)=>{const rule=ruleFor(p);return n>=rule.packQty*10?rule.tenCartons:n>=rule.packQty?rule.carton:rule.single};
  const percent=(p:Product,n:number,tier:Tier=user?.tier||"small")=>{
    const rule=ruleFor(p);const policy=tierPolicies[tier];
    if(policy.allBest||policy.bestCategories.includes(p.categoryEn)) return rule.tenCartons;
    return quantityPercent(n,p);
  };
  const price=(p:Product,n:number,tier:Tier=user?.tier||"small")=>variant(p).base*percent(p,n,tier)/100;
  const categories=useMemo(()=>catalogueGroups.map(g=>[g.vi,g.zh] as [string,string]),[]);
  const filtered=productList.filter(p=>(category==="all"||p.category===category)&&`${p.code} ${p.name} ${p.zh}`.toLowerCase().includes(search.toLowerCase()));
  const cartItems=productList.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]}));
  const total=cartItems.reduce((s,p)=>s+price(p,p.quantity)*p.quantity,0);
  const changeQty=(id:number,n:number)=>setQty(q=>({...q,[id]:Math.max(1,Math.floor(n||1))}));
  const add=(id:number,n?:number)=>{const amount=n||qty[id]||1;setCart(c=>({...c,[id]:(c[id]||0)+amount}));setToast(t("Đã thêm vào đơn hàng","已加入訂單"));setTimeout(()=>setToast(""),1500)};

  if(!user)return <main className="loginPage"><section className="loginBrand"><div className="brandMark">TĐ</div><p className="eyebrow">CỔNG ĐẶT HÀNG DÀNH CHO ĐẠI LÝ</p><h1>Đặt hàng Tân Đông<br/><em>nhanh hơn mỗi ngày.</em></h1><p>Giá theo cấp đại lý · Chiết khấu theo số lượng · Xác nhận bởi Tân Đông</p><div className="trustRow"><span>✓ Giá riêng bảo mật</span><span>✓ Chiết khấu rõ ràng</span><span>✓ Hỗ trợ Zalo</span></div></section><section className="loginPanel"><button className="langBtn" onClick={()=>setLang(lang==="vi"?"zh":"vi")}>{lang==="vi"?"中文":"VI"}</button><form className="loginCard" onSubmit={e=>{e.preventDefault();const c=customers.find(x=>x.username===username&&x.password===password);if(c)setUser(c)}}><div className="miniLogo"><b>TÂN ĐÔNG</b><small>PRO</small></div><h2>{t("Chào mừng trở lại","歡迎回來")}</h2><p>{t("Đăng nhập để xem giá và chiết khấu dành riêng","登入查看您的專屬價格與數量折扣")}</p><label>{t("Tên đăng nhập","使用者名稱")}<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>{t("Mật khẩu","密碼")}<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{t("Đăng nhập","登入")} <span>→</span></button><div className="demoBox"><b>{t("Tài khoản dùng thử","示範帳號")}</b>{customers.map(c=><button type="button" key={c.username} onClick={()=>setUsername(c.username)}>{c.username}</button>)}<small>{t("Mật khẩu: 123456 · Ba cấp giá","密碼：123456・三種客戶等級")}</small></div></form></section></main>;

  const tierLabel=t(tierInfo[user.tier].vi,tierInfo[user.tier].zh);
  const Card=({p}:{p:Product})=>{const n=qty[p.id]||1;const pc=percent(p,n);const v=variant(p);const packQty=packQtyFor(p);const best=tierPolicies[user.tier].allBest||tierPolicies[user.tier].bestCategories.includes(p.categoryEn);return <article className="productCard" onClick={()=>setSelected(p)}><div className="productVisual"><img src={p.image} alt={lang==="vi"?p.name:p.zh}/><small>{p.code}</small></div><div className="productInfo"><span className="tag">{lang==="vi"?p.category:p.categoryZh}</span><h3>{lang==="vi"?p.name:p.zh}</h3><select className="variantSelect" value={v.id} onClick={e=>e.stopPropagation()} onChange={e=>setVariantByProduct(x=>({...x,[p.id]:e.target.value}))}>{p.variants.map(x=><option value={x.id} key={x.id}>{lang==="vi"?x.label:x.labelZh} · {fmt(x.base)}</option>)}</select><div className="listPrice"><span>{t("Giá niêm yết theo quy cách","規格牌價")}</span><del>{fmt(v.base)}</del></div><div className="priceRow"><div><b>{fmt(price(p,n))}</b><small>{pc}% · {best?t("mức thấp nhất của danh mục","此分類最低價"):n>=packQty?t("giá theo số lượng","數量階梯價"):tierLabel}</small></div><button onClick={e=>{e.stopPropagation();add(p.id,n)}}>＋</button></div><div className="packHint">{t("1 thùng","1箱")} = {packQty} pcs</div><div className="cardQty" onClick={e=>e.stopPropagation()}><button onClick={()=>changeQty(p.id,n-1)}>−</button><input type="number" min="1" value={n} onChange={e=>changeQty(p.id,Number(e.target.value))}/><button onClick={()=>changeQty(p.id,n+1)}>＋</button><button className="cartonBtn" onClick={()=>changeQty(p.id,packQty)}>{t("1 thùng","1箱")} · {packQty}</button></div></div></article>};

  return <main className="appShell"><header className="topbar"><button className="logo" onClick={()=>setView("home")}><span>TĐ</span><b>TÂN ĐÔNG<small>PRO</small></b></button><div className="desktopSearch"><span>⌕</span><input placeholder={t("Tìm mã hoặc tên sản phẩm...","搜尋產品名稱或編號…")} value={search} onChange={e=>{setSearch(e.target.value);setView("products")}}/></div><div className="topActions"><button onClick={()=>setLang(lang==="vi"?"zh":"vi")}>{lang==="vi"?"中文":"VI"}</button><button onClick={()=>setAdmin(!admin)}>⚙ <span>{t("Quản trị","管理後台")}</span></button><button className="avatar" onClick={()=>setView("account")}>{user.name.slice(0,2)}</button></div></header>
  {admin?<Admin customers={customers} setCustomers={setCustomers} categoryRules={categoryRules} setCategoryRules={setCategoryRules} tierPolicies={tierPolicies} setTierPolicies={setTierPolicies} products={productList} setProducts={setProductList} close={()=>{setAdmin(false);setUser(customers.find(c=>c.username===user.username)||user)}} t={t}/>:<>
  {view==="home"&&<div className="page homePage"><section className="welcome"><div><p>{t("Xin chào,","您好，")}</p><h1>{user.name}</h1><span>{t("Đã áp dụng bảng giá","已套用價格層級")} · <b>{tierLabel}</b></span></div><button onClick={()=>setView("cart")}>{t("Đơn đang soạn","目前訂單")} <strong>{cartItems.length}</strong><small>{fmt(total)}</small></button></section><section className="quickGrid"><button className="quick orange" onClick={()=>setView("products")}><span className="icon">＋</span><span><b>{t("Đặt hàng nhanh","快速訂貨")}</b><small>{t("Chọn loại hàng và số lượng","選擇分類與數量")}</small></span></button><button className="quick" onClick={()=>setView("products")}><span className="icon">▦</span><span><b>{t("Chọn danh mục","依分類選貨")}</b><small>{t("Theo nhóm sản phẩm Tân Đông","依新東官網產品類別")}</small></span></button><button className="quick" onClick={()=>{add(1,100);add(4,50)}}><span className="icon">↻</span><span><b>{t("Mua lại","再次購買")}</b><small>{t("Từ đơn gần nhất","從最近訂單加入")}</small></span></button><button className="quick" onClick={()=>setView("videos")}><span className="icon">▶</span><span><b>{t("Video lắp đặt","安裝影片")}</b><small>{t("Xem hướng dẫn","觀看教學")}</small></span></button></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">{t("DANH MỤC SẢN PHẨM","產品分類")}</p><h2>{t("Chọn nhanh theo nhu cầu","依需求快速選擇")}</h2></div><button onClick={()=>setView("products")}>{t("Xem tất cả","查看全部")} →</button></div><div className="categoryGrid">{categories.map(([vi,zh],i)=><button key={vi} onClick={()=>{setCategory(vi);setView("products")}}><span>{i+1}</span><b>{lang==="vi"?vi:zh}</b><small>{productList.filter(p=>p.category===vi).length} {t("sản phẩm","項產品")}</small></button>)}</div></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">{t("SẢN PHẨM THƯỜNG MUA","常購產品")}</p><h2>{t("Đặt lại nhanh","快速再訂")}</h2></div></div><div className="products">{productList.slice(0,4).map(p=><Card key={p.id} p={p}/>)}</div></section></div>}
  {view==="products"&&<div className="page"><div className="pageTitle"><p className="eyebrow">CATALOGUE 2026</p><h1>{t("Sản phẩm Tân Đông","新東產品")}</h1><p>{tierLabel} · {t("Chiết khấu và số lượng mỗi thùng được đặt theo từng danh mục.","折扣與每箱數量依各產品分類設定。")}</p></div><div className="mobileSearch"><input placeholder={t("Tìm sản phẩm...","搜尋產品…")} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="chips"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>{t("Tất cả","全部")}</button>{categories.map(([vi,zh])=><button className={category===vi?"active":""} onClick={()=>setCategory(vi)} key={vi}>{lang==="vi"?vi:zh}</button>)}</div>{category!=="all"&&(()=>{const g=catalogueGroups.find(x=>x.vi===category);const r=g&&categoryRules[g.en];if(!g||!r)return null;const best=tierPolicies[user.tier].allBest||tierPolicies[user.tier].bestCategories.includes(g.en);return <div className="discountNotice"><b>{t(g.vi,g.zh)} · {tierLabel}</b><span>{t("1 thùng","1箱")} = <strong>{r.packQty} pcs</strong></span>{best?<span>{t("Áp dụng mức thấp nhất","直接最低價")} <strong>{r.tenCartons}%</strong></span>:<><span>1 pcs <strong>{r.single}%</strong></span><span>{r.packQty} pcs <strong>{r.carton}%</strong></span><span>{r.packQty*10} pcs <strong>{r.tenCartons}%</strong></span></>}<small>{t("Giá cập nhật theo số lượng nhập","價格依輸入數量即時更新")}</small></div>})()}<div className="products productsAll">{filtered.map(p=><Card key={p.id} p={p}/>)}</div></div>}
  {view==="cart"&&<Cart items={cartItems} total={total} cart={cart} setCart={setCart} price={price} percent={percent} lang={lang} user={user} t={t} goProducts={()=>setView("products")} submit={()=>{setCart({});setView("account");setToast(t("Đã gửi đơn · Chờ xác nhận","訂單已送出・等待確認"))}}/>}
  {view==="videos"&&<div className="page"><div className="pageTitle"><p className="eyebrow">TÂN ĐÔNG ACADEMY</p><h1>{t("Video hướng dẫn","影片教學")}</h1></div><div className="videoGrid">{[["Lắp phao cơ đúng cách","安裝水塔浮球"],["Kiểm tra dây cấp inox 304","304編織管品質測試"],["Thay dây sen chống xoắn","更換防纏繞花灑管"],["Cách chọn đầu nối","如何選擇接頭"]].map((v,i)=><article key={v[0]}><div className={`vthumb v${i}`}><span>▶</span><small>02:18</small></div><p>{t("HƯỚNG DẪN","教學影片")}</p><h3>{lang==="vi"?v[0]:v[1]}</h3><button>▶ {t("Xem video","觀看影片")}</button></article>)}</div></div>}
  {view==="account"&&<div className="page account"><div className="accountHero"><div className="bigAvatar">{user.name.slice(0,2)}</div><div><p>{t("TÀI KHOẢN ĐẠI LÝ","經銷商帳戶")}</p><h1>{user.name}</h1><span>{user.username} · {tierLabel}</span></div><button onClick={()=>setUser(null)}>{t("Đăng xuất","登出")}</button></div><div className="accountGrid"><section><h2>{t("Đơn hàng gần đây","最近訂單")}</h2><div className="order"><div><b>#TD-260812-08</b><small>12/08/2026</small></div><span className="pending">{t("Chờ xác nhận","等待確認")}</span><strong>4.860.000 ₫</strong><button onClick={()=>{add(1,100);setView("cart")}}>↻ {t("Đặt lại","再次訂購")}</button></div></section><aside><h2>{t("Cấp khách hàng","客戶等級")}</h2><p><b>{tierLabel}</b></p><p>{t("Bảng giá do Tân Đông quản lý.","價格表由新東後台管理。")}</p><hr/><p>⌖ {user.address}</p></aside></div></div>}
  </>}
  <nav className="bottomNav">{[["⌂","home","Trang chủ","首頁"],["▦","products","Sản phẩm","產品"],["＋","cart","Đặt hàng","訂貨"],["▶","videos","Video","影片"],["●","account","Của tôi","我的"]].map(n=><button key={n[1]} className={view===n[1]?"active":""} onClick={()=>{setAdmin(false);setView(n[1])}}><span>{n[0]}{n[1]==="cart"&&cartItems.length?<i>{cartItems.length}</i>:null}</span><small>{t(n[2],n[3])}</small></button>)}</nav>
  {selected&&<ProductModal p={selected} packQty={packQtyFor(selected)} n={qty[selected.id]||1} setN={n=>changeQty(selected.id,n)} selectedVariant={variant(selected)} setVariant={id=>setVariantByProduct(x=>({...x,[selected.id]:id}))} pc={percent(selected,qty[selected.id]||1)} unit={price(selected,qty[selected.id]||1)} tier={tierLabel} lang={lang} t={t} close={()=>setSelected(null)} add={()=>{add(selected.id,qty[selected.id]||1);setSelected(null)}}/>}{toast&&<div className="toast">✓ {toast}</div>}</main>;
}

function Cart({items,total,cart,setCart,price,percent,lang,user,t,goProducts,submit}:{items:(Product&{quantity:number})[];total:number;cart:Record<number,number>;setCart:React.Dispatch<React.SetStateAction<Record<number,number>>>;price:(p:Product,n:number)=>number;percent:(p:Product,n:number)=>number;lang:"vi"|"zh";user:Customer;t:(a:string,b:string)=>string;goProducts:()=>void;submit:()=>void}){
 return <div className="page narrow"><div className="pageTitle"><p className="eyebrow">{t("ĐƠN HÀNG MỚI","新訂單")}</p><h1>{t("Kiểm tra đơn hàng","確認訂單")}</h1></div>{items.length?<><div className="cartList">{items.map(p=><div className="cartItem" key={p.id}><img src={p.image} alt=""/><div><b>{lang==="vi"?p.name:p.zh}</b><small>{p.code} · <del>{fmt(p.variants[0].base)}</del> <strong>{fmt(price(p,p.quantity))}</strong> · {percent(p,p.quantity)}%</small></div><div className="stepper"><button onClick={()=>setCart({...cart,[p.id]:Math.max(1,p.quantity-1)})}>−</button><input type="number" value={p.quantity} onChange={e=>setCart({...cart,[p.id]:Math.max(1,Number(e.target.value))})}/><button onClick={()=>setCart({...cart,[p.id]:p.quantity+1})}>＋</button></div><strong>{fmt(price(p,p.quantity)*p.quantity)}</strong></div>)}</div><div className="summary"><div><span>{t("Tạm tính","小計")}</span><b>{fmt(total)}</b></div><div><span>{t("Giao đến","送貨地址")}</span><p>{user.address}</p></div><button className="primary" onClick={submit}>{t("Gửi đơn cho Tân Đông xác nhận","送出訂單，等待新東確認")} →</button><small>ⓘ {t("Hệ thống chỉ chọn một tỷ lệ giá cuối cùng, không cộng dồn chiết khấu.","系統只選擇一個最終價格百分比，不重複疊加折扣。")}</small></div></>:<div className="empty"><span>▤</span><h2>{t("Đơn hàng đang trống","訂單目前是空的")}</h2><button className="primary" onClick={goProducts}>{t("Chọn sản phẩm","選擇產品")}</button></div>}</div>
}

function ProductModal({p,packQty,n,setN,selectedVariant,setVariant,pc,unit,tier,lang,t,close,add}:{p:Product;packQty:number;n:number;setN:(n:number)=>void;selectedVariant:Variant;setVariant:(id:string)=>void;pc:number;unit:number;tier:string;lang:"vi"|"zh";t:(a:string,b:string)=>string;close:()=>void;add:()=>void}){
 return <div className="modalBackdrop" onClick={close}><section className="modal priceModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="detailVisual"><img src={p.image} alt=""/></div><p className="eyebrow">{p.code} · {lang==="vi"?p.category:p.categoryZh}</p><h2>{lang==="vi"?p.name:p.zh}</h2><label className="modalVariant">{t("Chọn quy cách","選擇規格")}<select value={selectedVariant.id} onChange={e=>setVariant(e.target.value)}>{p.variants.map(v=><option value={v.id} key={v.id}>{lang==="vi"?v.label:v.labelZh} · {fmt(v.base)}</option>)}</select></label><div className="modalPricing"><div><span>{t("Giá niêm yết quy cách","此規格牌價")}</span><del>{fmt(selectedVariant.base)}</del></div><div className="activePrice"><span>{t("Đơn giá hiện tại","目前單價")}</span><b>{fmt(unit)}</b></div><small>{tier} · {t("Thanh toán","支付牌價的")} {pc}%</small></div><div className="qtyPicker"><label>{t("Số lượng","訂購數量")}<div><button onClick={()=>setN(Math.max(1,n-1))}>−</button><input type="number" min="1" value={n} onChange={e=>setN(Math.max(1,Number(e.target.value)))}/><button onClick={()=>setN(n+1)}>＋</button></div></label><div className="quickQty"><button onClick={()=>setN(1)}>1 pcs</button><button onClick={()=>setN(packQty)}>{t("1 thùng","1箱")} ({packQty})</button><button onClick={()=>setN(packQty*10)}>{t("10 thùng","10箱")} ({packQty*10})</button></div></div><dl><div><dt>{t("Quy cách đóng gói","包裝數量")}</dt><dd>1 {t("thùng","箱")} = {packQty} pcs</dd></div><div><dt>{t("Thành tiền","總額")}</dt><dd>{fmt(unit*n)}</dd></div></dl><button className="primary" onClick={add}>{t("Thêm vào đơn hàng","加入訂單")} <span>＋</span></button></section></div>
}

function Admin({customers,setCustomers,categoryRules,setCategoryRules,tierPolicies,setTierPolicies,products,setProducts,close,t}:{customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>;categoryRules:Record<string,CategoryRule>;setCategoryRules:React.Dispatch<React.SetStateAction<Record<string,CategoryRule>>>;tierPolicies:TierPolicy;setTierPolicies:React.Dispatch<React.SetStateAction<TierPolicy>>;products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;close:()=>void;t:(a:string,b:string)=>string}){
 const [tab,setTab]=useState("discounts");const [draft,setDraft]=useState(categoryRules);const [saved,setSaved]=useState(false);const [productSearch,setProductSearch]=useState("");const [showNewCustomer,setShowNewCustomer]=useState(false);const [newCustomer,setNewCustomer]=useState<Customer>({username:"",password:"123456",name:"",tier:"small",address:""});
 const nav=[["▤","orders",t("Đơn hàng","訂單管理")],["●","customers",t("Khách hàng","客戶管理")],["♟","tiers",t("Cấp khách hàng","客戶等級")],["％","discounts",t("Chiết khấu số lượng","數量折扣")],["▦","products",t("Sản phẩm","產品管理")]];
 const title:Record<string,string>={orders:t("Quản lý đơn hàng","訂單管理"),customers:t("Phân loại khách hàng","客戶分類管理"),tiers:t("Quyền mức thấp nhất theo cấp khách","盤商分類最低價權限"),discounts:t("Chiết khấu theo danh mục","產品類別折扣設定"),products:t("Danh mục & sản phẩm","分類與產品管理")};
 const updateCategory=(category:string,key:keyof CategoryRule,v:number)=>setDraft(d=>({...d,[category]:{...d[category],[key]:key==="packQty"?Math.max(1,Math.floor(v||1)):Math.min(100,Math.max(1,v||1))}}));
 const toggleBestCategory=(tier:Tier,category:string,checked:boolean)=>setTierPolicies(p=>({...p,[tier]:{...p[tier],bestCategories:checked?[...new Set([...p[tier].bestCategories,category])]:p[tier].bestCategories.filter(x=>x!==category)}}));
 const updateBase=(productId:number,variantId:string,value:number)=>setProducts(list=>list.map(p=>p.id===productId?{...p,variants:p.variants.map(v=>v.id===variantId?{...v,base:Math.max(0,value||0)}:v)}:p));
 const visibleProducts=products.filter(p=>`${p.code} ${p.category} ${p.categoryZh}`.toLowerCase().includes(productSearch.toLowerCase()));
 return <div className="admin"><aside><div className="logo"><span>TĐ</span><b>TÂN ĐÔNG<small>ADMIN</small></b></div><p>{t("QUẢN LÝ HỆ THỐNG","系統管理")}</p>{nav.map(x=><button className={tab===x[1]?"active":""} onClick={()=>setTab(x[1])} key={x[1]}><i>{x[0]}</i>{x[2]}</button>)}<button className="back" onClick={close}>← {t("Về trang đại lý","返回經銷商頁")}</button></aside><section className="adminMain"><div className="adminHead"><div><p>TÂN ĐÔNG PRO</p><h1>{title[tab]}</h1></div>{tab==="discounts"&&<button onClick={()=>{setCategoryRules(draft);setSaved(true);setTimeout(()=>setSaved(false),1600)}}>{saved?t("✓ Đã áp dụng","✓ 已套用"):t("Lưu & áp dụng","儲存並套用")}</button>}{tab==="customers"&&<button onClick={()=>setShowNewCustomer(true)}>＋ {t("Thêm username","新增Username")}</button>}</div>
 {(tab==="tiers"||tab==="discounts")&&<div className="adminIntro"><b>{tab==="tiers"?t("Chọn danh mục được dùng ngay mức thấp nhất cho từng cấp khách.","分别为大盘、中盘、小盘选择可直接使用最低价的产品类别。") : t("Mỗi danh mục tự đặt số pcs/thùng và ba mức giá theo số lượng.","每个产品类别分别设定每箱件数及三个数量价格。")}</b><span>{t("Một dòng hàng chỉ áp dụng một tỷ lệ cuối cùng, không cộng dồn.","每一笔商品只套用一个最终百分比，不重复叠加。")}</span></div>}
 {tab==="tiers"&&<div className="tierPolicyGrid">{(["large","medium","small"] as Tier[]).map((tier,i)=><article className="tierPolicyCard" key={tier}><div className="tierPolicyTitle"><span className={`tierIcon tier${i}`}>{i+1}</span><div><p>{tierInfo[tier].code}</p><h2>{t(tierInfo[tier].vi,tierInfo[tier].zh)}</h2><small>{customers.filter(c=>c.tier===tier).length} {t("tài khoản","個帳號")}</small></div></div><label className="allBest"><input type="checkbox" checked={tierPolicies[tier].allBest} onChange={e=>setTierPolicies(p=>({...p,[tier]:{...p[tier],allBest:e.target.checked}}))}/><span><b>{t("Tất cả danh mục dùng mức thấp nhất","全部类别直接使用最低价")}</b><small>{t("Bật mục này sẽ bỏ qua bậc số lượng","开启后不再判断订购数量")}</small></span></label><div className={tierPolicies[tier].allBest?"tierCategoryChoices disabled":"tierCategoryChoices"}>{catalogueGroups.map(g=><label key={g.en}><input type="checkbox" disabled={tierPolicies[tier].allBest} checked={tierPolicies[tier].bestCategories.includes(g.en)} onChange={e=>toggleBestCategory(tier,g.en,e.target.checked)}/><span>{t(g.vi,g.zh)}</span><strong>{draft[g.en].tenCartons}%</strong></label>)}</div></article>)}</div>}
 {tab==="discounts"&&<div className="categoryDiscountStack">{catalogueGroups.map((g,i)=>{const rule=draft[g.en];return <article className="categoryDiscountCard" key={g.en}><div className="categoryDiscountTitle"><span>{i+1}</span><div><em>{g.en}</em><h2>{t(g.vi,g.zh)}</h2></div><label><small>{t("PCS / THÙNG","每箱PCS")}</small><input type="number" min="1" value={rule.packQty} onChange={e=>updateCategory(g.en,"packQty",Number(e.target.value))}/></label></div><div className="categoryDiscountSteps"><label><span>1 pcs</span><div><input type="number" min="1" max="100" value={rule.single} onChange={e=>updateCategory(g.en,"single",Number(e.target.value))}/><i>%</i></div></label><label><span>{rule.packQty} pcs · 1 {t("thùng","箱")}</span><div><input type="number" min="1" max="100" value={rule.carton} onChange={e=>updateCategory(g.en,"carton",Number(e.target.value))}/><i>%</i></div></label><label className="bestStep"><span>{rule.packQty*10} pcs · 10 {t("thùng","箱")}</span><div><input type="number" min="1" max="100" value={rule.tenCartons} onChange={e=>updateCategory(g.en,"tenCartons",Number(e.target.value))}/><i>%</i></div><small>{t("Mức thấp nhất","最低价")}</small></label></div></article>})}<div className="formulaBox"><b>{t("Thứ tự tính giá","计价顺序")}</b><code>{t("Giá niêm yết quy cách × một tỷ lệ cuối cùng của danh mục","规格牌价 × 该类别唯一的最终百分比")}</code><small>{t("Nếu cấp khách được cấp quyền mức thấp nhất cho danh mục, dùng ngay mức 10 thùng; nếu không, hệ thống xét số lượng 1 pcs / 1 thùng / 10 thùng.","若该盘商等级拥有此类别最低价权限，直接使用10箱百分比；否则依1件／1箱／10箱数量判断。")}</small></div></div>}
 {tab==="customers"&&<div className="adminTable"><div className="tableTools"><b>{t("Username & cấp khách hàng","Username與客戶等級")}</b><span className="countPill">{customers.length} usernames</span></div>{showNewCustomer&&<form className="newCustomerForm" onSubmit={e=>{e.preventDefault();if(!newCustomer.username||!newCustomer.name||customers.some(c=>c.username===newCustomer.username))return;setCustomers(x=>[...x,newCustomer]);setNewCustomer({username:"",password:"123456",name:"",tier:"small",address:""});setShowNewCustomer(false)}}><input required placeholder="Username" value={newCustomer.username} onChange={e=>setNewCustomer(x=>({...x,username:e.target.value.trim().toLowerCase()}))}/><input required placeholder={t("Tên khách hàng","客戶名稱")} value={newCustomer.name} onChange={e=>setNewCustomer(x=>({...x,name:e.target.value}))}/><select value={newCustomer.tier} onChange={e=>setNewCustomer(x=>({...x,tier:e.target.value as Tier}))}><option value="large">{t("Đại lý lớn","大盤")}</option><option value="medium">{t("Đại lý vừa","中盤")}</option><option value="small">{t("Cửa hàng","小盤")}</option></select><input placeholder={t("Địa chỉ giao hàng","送貨地址")} value={newCustomer.address} onChange={e=>setNewCustomer(x=>({...x,address:e.target.value}))}/><input value={newCustomer.password} onChange={e=>setNewCustomer(x=>({...x,password:e.target.value}))}/><button className="primary">{t("Tạo username","建立Username")}</button></form>}<div className="customerHeader"><span>USERNAME / {t("KHÁCH HÀNG","客戶")}</span><span>{t("CẤP HIỆN TẠI","目前等級")}</span><span>{t("QUYỀN XEM GIÁ","價格權限")}</span></div>{customers.map(c=><div className="customerRow" key={c.username}><span><b>{c.name}</b><small>@{c.username}</small></span><select value={c.tier} onChange={e=>setCustomers(list=>list.map(x=>x.username===c.username?{...x,tier:e.target.value as Tier}:x))}><option value="large">{t("Đại lý lớn / Đại bàn","大盤客戶")}</option><option value="medium">{t("Đại lý vừa / Trung bàn","中盤客戶")}</option><option value="small">{t("Cửa hàng / Tiểu bàn","小盤客戶")}</option></select><span className="permission">✓ {t("Chỉ giá của cấp này","僅顯示此等級價格")}</span></div>)}</div>}
 {tab==="products"&&<div className="productAdminStack"><div className="adminIntro"><b>{t("Mỗi mã sản phẩm và mỗi quy cách có giá niêm yết riêng.","每個產品編號、每個規格都有獨立牌價。")}</b><span>{t("Chiết khấu và số pcs/thùng được quản lý tập trung tại mục Chiết khấu theo danh mục.","折扣与每箱pcs统一在「产品类别折扣」管理。")}</span></div><div className="adminTable"><div className="tableTools"><div><b>{t("4 danh mục theo website cũ","舊官網圈選的4個分類")}</b><small>{products.length} {t("sản phẩm đã nhập","項產品已匯入")}</small></div><span className="countPill">4 {t("danh mục","個分類")}</span></div>{catalogueGroups.map((g,i)=><button className="categoryAdminRow categorySummary" key={g.en} onClick={()=>setProductSearch(g.vi)}><span>{i+1}</span><b><em>{g.en}</em>{t(g.vi,g.zh)}</b><small>{products.filter(p=>p.category===g.vi).length} {t("sản phẩm","項產品")} · 1 {t("thùng","箱")} = {categoryRules[g.en].packQty} pcs</small><strong>→</strong></button>)}</div><div className="adminTable productPriceTable"><div className="tableTools"><div><b>{t("Bảng giá theo mã + quy cách","依產品編號＋規格設定牌價")}</b><small>{t("Đơn vị: VND / pcs","單位：VND／件")}</small></div><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder={t("Tìm mã sản phẩm...","搜尋產品編號…")}/></div><div className="variantPriceHeader"><span>{t("SẢN PHẨM","產品")}</span><span>{t("QUY CÁCH","規格")}</span><span>{t("GIÁ NIÊM YẾT","牌價")}</span><span>{t("MỨC THẤP NHẤT","最低价")}</span></div>{visibleProducts.map(p=><div className="variantProduct" key={p.id}><div className="variantProductTitle"><img src={p.image} alt=""/><span><b>{p.code}</b><small>{t(p.category,p.categoryZh)} · {categoryRules[p.categoryEn].packQty} pcs / {t("thùng","箱")}</small></span></div>{p.variants.map(v=><div className="variantPriceRow" key={v.id}><span>{t(v.label,v.labelZh)}</span><label><input type="number" min="0" step="1000" value={v.base} onChange={e=>updateBase(p.id,v.id,Number(e.target.value))}/><i>₫</i></label><strong>{fmt(v.base*categoryRules[p.categoryEn].tenCartons/100)}</strong></div>)}</div>)}</div></div>}
 {tab==="orders"&&<div className="adminTable"><div className="tableTools"><b>{t("Đơn hàng gần đây","最近訂單")}</b></div>{customers.concat(customers).slice(0,5).map((c,i)=><div className="tr" key={i}><span><b>#TD-260812-0{8-i}</b><small>{c.name} · {t(tierInfo[c.tier].vi,tierInfo[c.tier].zh)}</small></span><span>12/08/2026</span><span><i className="status">{t("Chờ xác nhận","等待確認")}</i></span><span><b>{[4860000,7325000,2190000,8920000,3450000][i].toLocaleString("vi-VN")} ₫</b></span></div>)}</div>}
 <div className="adminNote">ⓘ {t("Bản mẫu quản trị — dữ liệu mô phỏng, chưa kết nối ERP.","管理後台原型——目前為模擬資料，尚未連接ERP。")}</div></section></div>
}
