"use client";

import { useMemo, useState } from "react";

type Tier = "large" | "medium" | "small";
type Rule = { single: number; carton: number; tenCartons: number };
type Customer = { username: string; password: string; name: string; tier: Tier; address: string };
type Product = { id:number; code:string; category:string; categoryZh:string; categoryEn:string; name:string; zh:string; spec:string; pack:string; packZh:string; packQty:number; base:number; image:string };

const tierInfo:Record<Tier,{vi:string;zh:string;code:string}> = {
  large:{vi:"Đại lý lớn",zh:"大盤客戶",code:"ĐẠI BÀN"},
  medium:{vi:"Đại lý vừa",zh:"中盤客戶",code:"TRUNG BÀN"},
  small:{vi:"Cửa hàng bán lẻ",zh:"小盤客戶",code:"TIỂU BÀN"},
};
const initialCustomers:Customer[] = [
  {username:"minhphat",password:"123456",name:"VLXD Minh Phát",tier:"large",address:"128 Nguyễn Văn Linh, Q.7, TP.HCM"},
  {username:"anphu",password:"123456",name:"Điện Nước An Phú",tier:"medium",address:"42 Lê Văn Việt, TP. Thủ Đức"},
  {username:"hoangnam",password:"123456",name:"Cửa hàng Hoàng Nam",tier:"small",address:"19 QL1A, Bình Tân, TP.HCM"},
];
const initialRules:Record<Tier,Rule> = {
  large:{single:85,carton:80,tenCartons:75},
  medium:{single:92,carton:86,tenCartons:80},
  small:{single:100,carton:90,tenCartons:80},
};
const catalogueGroups:{en:string;vi:string;zh:string;packQty:number;items:[string,string][]}[] = [
  {en:"FLEXIBLE HOSE",vi:"Dây cấp nước",zh:"給水軟管",packQty:100,items:[
    ["102XI05","https://www.shintung-onspa.com/upload/2018/10/18/1539847068.jpg"],["102XI05","https://www.shintung-onspa.com/upload/2018/10/18/1539846019.jpg"],["102XD01","https://www.shintung-onspa.com/upload/2016/12/09/1481272647.jpg"],["102XS01","https://www.shintung-onspa.com/cache/fillw_737h_737/2cc328c791c56edaff2f700cd02b90cd1501661507.jpg.png"],["102XL01","https://www.shintung-onspa.com/upload/2016/12/09/1481261489.jpg"],["102XS03","https://www.shintung-onspa.com/upload/2016/12/09/1481264540.jpg"],["102XI02","https://www.shintung-onspa.com/upload/2016/12/09/1481262576.jpg"],["102XI01","https://www.shintung-onspa.com/cache/fillw_737h_737/952984cf71ccf086b44e5d391cfb0f901477662560.jpg.png"],["102IC01","https://www.shintung-onspa.com/upload/2016/12/09/1481266326.jpg"],["102XT04","https://www.shintung-onspa.com/cache/fillw_737h_737/c5bf50b6c9cf09a15a56a939d6596ade1735978152.png.png"],["102XT01","https://www.shintung-onspa.com/upload/2016/12/08/1481173708.jpg"],["102MG01","https://www.shintung-onspa.com/upload/2016/12/09/1481269694.jpg"],["102DG01","https://www.shintung-onspa.com/upload/2016/12/09/1481260035.jpg"]]},
  {en:"SHOWER",vi:"Vòi sen",zh:"花灑",packQty:50,items:[
    ["103S283201","https://www.shintung-onspa.com/upload/2024/09/07/1725681592.jpg"],["103S183204","https://www.shintung-onspa.com/upload/2024/09/06/1725612951.jpg"],["103S282201","https://www.shintung-onspa.com/upload/2024/09/06/1725614008.jpg"],["103S182204","https://www.shintung-onspa.com/upload/2024/09/06/1725610345.jpg"],["103SM32101","https://www.shintung-onspa.com/upload/2024/09/06/1725605053.jpg"],["103SM31101","https://www.shintung-onspa.com/upload/2024/09/06/1725596430.jpg"],["103S194121","https://www.shintung-onspa.com/upload/2024/09/06/1725594057.jpg"],["103S194111","https://www.shintung-onspa.com/upload/2024/09/06/1725592968.jpg"],["103S194101","https://www.shintung-onspa.com/upload/2024/09/06/1725590166.jpg"],["103S193101","https://www.shintung-onspa.com/upload/2025/05/09/1746782118.jpg"],["103SM00013","https://www.shintung-onspa.com/upload/2022/09/19/1663571546.jpg"],["103SM00011","https://www.shintung-onspa.com/upload/2020/11/02/1604302308.jpg"],["103SM00012","https://www.shintung-onspa.com/upload/2020/11/02/1604300335.jpg"],["103SM00004","https://www.shintung-onspa.com/upload/2017/09/07/1504758595.jpg"],["103SM00001","https://www.shintung-onspa.com/upload/2016/12/14/1481698159.jpg"],["103SM00002","https://www.shintung-onspa.com/upload/2016/12/14/1481698107.jpg"],["103SM00003","https://www.shintung-onspa.com/upload/2016/12/14/1481698042.jpg"],["103S101","https://www.shintung-onspa.com/upload/2016/12/14/1481698614.jpg"],["103S103","https://www.shintung-onspa.com/upload/2016/12/14/1481698539.jpg"],["103S110","https://www.shintung-onspa.com/upload/2016/12/14/1481698426.jpg"],["103S111","https://www.shintung-onspa.com/upload/2016/12/14/1481698363.jpg"],["103S112","https://www.shintung-onspa.com/upload/2016/12/14/1481698280.jpg"],["103S205","https://www.shintung-onspa.com/cache/fillw_737h_737/ce6b7038aedb78a230d64358560710ec1504760822.jpg.png"],["103S204","https://www.shintung-onspa.com/cache/fillw_737h_737/c2f3cd57c61df38095befca5908dcf001504760777.jpg.png"],["103S2082","https://www.shintung-onspa.com/upload/2017/09/07/1504758960.jpg"],["103S24B","https://www.shintung-onspa.com/upload/2017/09/07/1504758979.jpg"],["103S206","https://www.shintung-onspa.com/upload/2017/09/07/1504759022.jpg"],["103S209","https://www.shintung-onspa.com/upload/2017/09/07/1504759043.jpg"],["103S292","https://www.shintung-onspa.com/upload/2017/09/07/1504759138.jpg"],["103S209204","https://www.shintung-onspa.com/upload/2017/09/07/1504760212.jpg"],["103S209205","https://www.shintung-onspa.com/upload/2017/09/07/1504759914.jpg"],["103PMSX01","https://www.shintung-onspa.com/upload/2016/12/14/1481699580.jpg"],["103PMSX03","https://www.shintung-onspa.com/upload/2016/12/14/1481699542.jpg"],["102TC01","https://www.shintung-onspa.com/upload/2017/09/07/1504761839.jpg"],["102TC04","https://www.shintung-onspa.com/upload/2017/09/07/1504761857.jpg"],["102TC03","https://www.shintung-onspa.com/upload/2017/09/07/1504761868.jpg"]]},
  {en:"SHATTAF",vi:"Vòi xịt vệ sinh",zh:"沖洗器",packQty:40,items:[
    ["104A39202","https://www.shintung-onspa.com/upload/2020/10/13/1602582716.jpg"],["104A39201","https://www.shintung-onspa.com/upload/2020/10/13/1602573182.jpg"],["104A141","https://www.shintung-onspa.com/upload/2016/12/16/1481864903.jpg"],["104A4X2","https://www.shintung-onspa.com/upload/2016/12/16/1481865214.jpg"],["104A4G2","https://www.shintung-onspa.com/upload/2016/12/16/1481865357.jpg"],["104A4G1","https://www.shintung-onspa.com/upload/2016/12/16/1481865523.jpg"],["104A4X1","https://www.shintung-onspa.com/upload/2016/12/16/1481865606.jpg"],["104A3801","https://www.shintung-onspa.com/upload/2016/12/16/1481864770.jpg"],["104A33201","https://www.shintung-onspa.com/upload/2016/12/16/1481864331.jpg"],["104A32201","https://www.shintung-onspa.com/upload/2016/12/16/1481864522.jpg"],["104A4F1","https://www.shintung-onspa.com/cache/fillw_737h_737/d219eb99714a2caf95ec59fc84939eb31489650246.jpg.png"],["104A4F2","https://www.shintung-onspa.com/upload/2016/12/16/1481865286.jpg"],["104A31201","https://www.shintung-onspa.com/upload/2016/12/16/1481864710.jpg"],["104A37201","https://www.shintung-onspa.com/upload/2016/12/16/1481863941.jpg"],["104A30201","https://www.shintung-onspa.com/upload/2016/12/16/1481864833.jpg"],["104A222","https://www.shintung-onspa.com/upload/2016/12/16/1481864871.jpg"],["104A131","https://www.shintung-onspa.com/upload/2016/12/16/1481865080.jpg"],["104A132","https://www.shintung-onspa.com/upload/2016/12/16/1481865014.jpg"],["104A34201","https://www.shintung-onspa.com/upload/2016/12/16/1481863765.jpg"],["104A35201","https://www.shintung-onspa.com/cache/fillw_737h_737/4c5c6db2d77467367df9a61ab8d72d151489645898.jpg.png"],["104A101","https://www.shintung-onspa.com/upload/2016/12/16/1481865479.jpg"],["104A102","https://www.shintung-onspa.com/upload/2016/12/16/1481865115.jpg"],["104A36201","https://www.shintung-onspa.com/upload/2016/12/16/1481864080.jpg"],["104PTEX05","https://www.shintung-onspa.com/upload/2016/12/16/1481864177.jpg"],["104PTEX03","https://www.shintung-onspa.com/upload/2016/12/16/1481864214.jpg"],["104PTEX02-XI","https://www.shintung-onspa.com/upload/2016/12/16/1481864267.jpg"],["104PTEX01","https://www.shintung-onspa.com/upload/2016/12/16/1481864292.jpg"]]},
  {en:"WATER LEVEL CONTROL",vi:"Van phao bồn nước",zh:"水位控制器",packQty:20,items:[
    ["101CTP015","https://www.shintung-onspa.com/upload/2017/01/22/1485074840.jpg"],["101CTP010","https://www.shintung-onspa.com/cache/fillw_737h_737/52dd40d7128958429069aebaf513af5f1489553320.jpg.png"]]},
];
const initialProducts:Product[] = catalogueGroups.flatMap((group,groupIndex)=>group.items.map(([code,image],itemIndex)=>({
  id:groupIndex*100+itemIndex+1,code,category:group.vi,categoryZh:group.zh,categoryEn:group.en,
  name:`${group.vi} ${code}`,zh:`${group.zh} ${code}`,spec:"Dữ liệu quy cách mẫu · Chờ ERP xác nhận",
  pack:`${group.packQty} pcs / thùng`,packZh:`${group.packQty}件／箱`,packQty:group.packQty,
  base:[32000,118000,86000,185000][groupIndex]+itemIndex*2500,image,
})));
const fmt=(n:number)=>new Intl.NumberFormat("vi-VN").format(Math.round(n/100)*100)+" ₫";

export default function Home(){
  const [customers,setCustomers]=useState(initialCustomers);
  const [rules,setRules]=useState(initialRules);
  const [productList,setProductList]=useState(initialProducts);
  const [user,setUser]=useState<Customer|null>(null);
  const [username,setUsername]=useState("minhphat");
  const [password,setPassword]=useState("123456");
  const [lang,setLang]=useState<"vi"|"zh">("vi");
  const [view,setView]=useState("home");
  const [admin,setAdmin]=useState(false);
  const [category,setCategory]=useState("all");
  const [search,setSearch]=useState("");
  const [qty,setQty]=useState<Record<number,number>>({});
  const [cart,setCart]=useState<Record<number,number>>({});
  const [selected,setSelected]=useState<Product|null>(null);
  const [toast,setToast]=useState("");
  const t=(vi:string,zh:string)=>lang==="vi"?vi:zh;
  const percent=(p:Product,n:number,tier:Tier=user?.tier||"small")=>n>=p.packQty*10?rules[tier].tenCartons:n>=p.packQty?rules[tier].carton:rules[tier].single;
  const price=(p:Product,n:number,tier:Tier=user?.tier||"small")=>p.base*percent(p,n,tier)/100;
  const categories=useMemo(()=>catalogueGroups.map(g=>[g.vi,g.zh] as [string,string]),[]);
  const filtered=productList.filter(p=>(category==="all"||p.category===category)&&`${p.code} ${p.name} ${p.zh}`.toLowerCase().includes(search.toLowerCase()));
  const cartItems=productList.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]}));
  const total=cartItems.reduce((s,p)=>s+price(p,p.quantity)*p.quantity,0);
  const changeQty=(id:number,n:number)=>setQty(q=>({...q,[id]:Math.max(1,Math.floor(n||1))}));
  const add=(id:number,n?:number)=>{const amount=n||qty[id]||1;setCart(c=>({...c,[id]:(c[id]||0)+amount}));setToast(t("Đã thêm vào đơn hàng","已加入訂單"));setTimeout(()=>setToast(""),1500)};

  if(!user)return <main className="loginPage"><section className="loginBrand"><div className="brandMark">TĐ</div><p className="eyebrow">CỔNG ĐẶT HÀNG DÀNH CHO ĐẠI LÝ</p><h1>Đặt hàng Tân Đông<br/><em>nhanh hơn mỗi ngày.</em></h1><p>Giá theo cấp đại lý · Chiết khấu theo số lượng · Xác nhận bởi Tân Đông</p><div className="trustRow"><span>✓ Giá riêng bảo mật</span><span>✓ Chiết khấu rõ ràng</span><span>✓ Hỗ trợ Zalo</span></div></section><section className="loginPanel"><button className="langBtn" onClick={()=>setLang(lang==="vi"?"zh":"vi")}>{lang==="vi"?"中文":"VI"}</button><form className="loginCard" onSubmit={e=>{e.preventDefault();const c=customers.find(x=>x.username===username&&x.password===password);if(c)setUser(c)}}><div className="miniLogo"><b>TÂN ĐÔNG</b><small>PRO</small></div><h2>{t("Chào mừng trở lại","歡迎回來")}</h2><p>{t("Đăng nhập để xem giá và chiết khấu dành riêng","登入查看您的專屬價格與數量折扣")}</p><label>{t("Tên đăng nhập","使用者名稱")}<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>{t("Mật khẩu","密碼")}<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{t("Đăng nhập","登入")} <span>→</span></button><div className="demoBox"><b>{t("Tài khoản dùng thử","示範帳號")}</b>{customers.map(c=><button type="button" key={c.username} onClick={()=>setUsername(c.username)}>{c.username}</button>)}<small>{t("Mật khẩu: 123456 · Ba cấp giá","密碼：123456・三種客戶等級")}</small></div></form></section></main>;

  const tierLabel=t(tierInfo[user.tier].vi,tierInfo[user.tier].zh);
  const Card=({p}:{p:Product})=>{const n=qty[p.id]||1;const pc=percent(p,n);return <article className="productCard" onClick={()=>setSelected(p)}><div className="productVisual"><img src={p.image} alt={lang==="vi"?p.name:p.zh}/><small>{p.code}</small></div><div className="productInfo"><span className="tag">{lang==="vi"?p.category:p.categoryZh}</span><h3>{lang==="vi"?p.name:p.zh}</h3><p>{p.spec}</p><div className="listPrice"><span>{t("Giá niêm yết","牌價")}</span><del>{fmt(p.base)}</del></div><div className="priceRow"><div><b>{fmt(price(p,n))}</b><small>{pc}% · {n>=p.packQty?t("giá số lượng","數量價"):tierLabel}</small></div><button onClick={e=>{e.stopPropagation();add(p.id,n)}}>＋</button></div><div className="cardQty" onClick={e=>e.stopPropagation()}><button onClick={()=>changeQty(p.id,n-1)}>−</button><input type="number" min="1" value={n} onChange={e=>changeQty(p.id,Number(e.target.value))}/><button onClick={()=>changeQty(p.id,n+1)}>＋</button><button className="cartonBtn" onClick={()=>changeQty(p.id,p.packQty)}>{t("1 thùng","1箱")}</button></div></div></article>};

  return <main className="appShell"><header className="topbar"><button className="logo" onClick={()=>setView("home")}><span>TĐ</span><b>TÂN ĐÔNG<small>PRO</small></b></button><div className="desktopSearch"><span>⌕</span><input placeholder={t("Tìm mã hoặc tên sản phẩm...","搜尋產品名稱或編號…")} value={search} onChange={e=>{setSearch(e.target.value);setView("products")}}/></div><div className="topActions"><button onClick={()=>setLang(lang==="vi"?"zh":"vi")}>{lang==="vi"?"中文":"VI"}</button><button onClick={()=>setAdmin(!admin)}>⚙ <span>{t("Quản trị","管理後台")}</span></button><button className="avatar" onClick={()=>setView("account")}>{user.name.slice(0,2)}</button></div></header>
  {admin?<Admin customers={customers} setCustomers={setCustomers} rules={rules} setRules={setRules} products={productList} setProducts={setProductList} close={()=>{setAdmin(false);setUser(customers.find(c=>c.username===user.username)||user)}} t={t}/>:<>
  {view==="home"&&<div className="page homePage"><section className="welcome"><div><p>{t("Xin chào,","您好，")}</p><h1>{user.name}</h1><span>{t("Đã áp dụng bảng giá","已套用價格層級")} · <b>{tierLabel}</b></span></div><button onClick={()=>setView("cart")}>{t("Đơn đang soạn","目前訂單")} <strong>{cartItems.length}</strong><small>{fmt(total)}</small></button></section><section className="quickGrid"><button className="quick orange" onClick={()=>setView("products")}><span className="icon">＋</span><span><b>{t("Đặt hàng nhanh","快速訂貨")}</b><small>{t("Chọn loại hàng và số lượng","選擇分類與數量")}</small></span></button><button className="quick" onClick={()=>setView("products")}><span className="icon">▦</span><span><b>{t("Chọn danh mục","依分類選貨")}</b><small>{t("Theo nhóm sản phẩm Tân Đông","依新東官網產品類別")}</small></span></button><button className="quick" onClick={()=>{add(1,100);add(4,50)}}><span className="icon">↻</span><span><b>{t("Mua lại","再次購買")}</b><small>{t("Từ đơn gần nhất","從最近訂單加入")}</small></span></button><button className="quick" onClick={()=>setView("videos")}><span className="icon">▶</span><span><b>{t("Video lắp đặt","安裝影片")}</b><small>{t("Xem hướng dẫn","觀看教學")}</small></span></button></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">{t("DANH MỤC SẢN PHẨM","產品分類")}</p><h2>{t("Chọn nhanh theo nhu cầu","依需求快速選擇")}</h2></div><button onClick={()=>setView("products")}>{t("Xem tất cả","查看全部")} →</button></div><div className="categoryGrid">{categories.map(([vi,zh],i)=><button key={vi} onClick={()=>{setCategory(vi);setView("products")}}><span>{i+1}</span><b>{lang==="vi"?vi:zh}</b><small>{productList.filter(p=>p.category===vi).length} {t("sản phẩm","項產品")}</small></button>)}</div></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">{t("SẢN PHẨM THƯỜNG MUA","常購產品")}</p><h2>{t("Đặt lại nhanh","快速再訂")}</h2></div></div><div className="products">{productList.slice(0,4).map(p=><Card key={p.id} p={p}/>)}</div></section></div>}
  {view==="products"&&<div className="page"><div className="pageTitle"><p className="eyebrow">CATALOGUE 2026</p><h1>{t("Sản phẩm Tân Đông","新東產品")}</h1><p>{tierLabel} · {t("Giá tự đổi theo số lượng đặt.","價格會依訂購數量自動調整。")}</p></div><div className="mobileSearch"><input placeholder={t("Tìm sản phẩm...","搜尋產品…")} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="chips"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>{t("Tất cả","全部")}</button>{categories.map(([vi,zh])=><button className={category===vi?"active":""} onClick={()=>setCategory(vi)} key={vi}>{lang==="vi"?vi:zh}</button>)}</div><div className="discountNotice"><b>{t("Chiết khấu số lượng của bạn","您的數量折扣")}</b><span>1 pcs <strong>{rules[user.tier].single}%</strong></span><span>{t("1 thùng","1箱")} <strong>{rules[user.tier].carton}%</strong></span><span>{t("10 thùng","10箱")} <strong>{rules[user.tier].tenCartons}%</strong></span><small>{t("% giá niêm yết","牌價百分比")}</small></div><div className="products productsAll">{filtered.map(p=><Card key={p.id} p={p}/>)}</div></div>}
  {view==="cart"&&<Cart items={cartItems} total={total} cart={cart} setCart={setCart} price={price} percent={percent} lang={lang} user={user} t={t} goProducts={()=>setView("products")} submit={()=>{setCart({});setView("account");setToast(t("Đã gửi đơn · Chờ xác nhận","訂單已送出・等待確認"))}}/>}
  {view==="videos"&&<div className="page"><div className="pageTitle"><p className="eyebrow">TÂN ĐÔNG ACADEMY</p><h1>{t("Video hướng dẫn","影片教學")}</h1></div><div className="videoGrid">{[["Lắp phao cơ đúng cách","安裝水塔浮球"],["Kiểm tra dây cấp inox 304","304編織管品質測試"],["Thay dây sen chống xoắn","更換防纏繞花灑管"],["Cách chọn đầu nối","如何選擇接頭"]].map((v,i)=><article key={v[0]}><div className={`vthumb v${i}`}><span>▶</span><small>02:18</small></div><p>{t("HƯỚNG DẪN","教學影片")}</p><h3>{lang==="vi"?v[0]:v[1]}</h3><button>▶ {t("Xem video","觀看影片")}</button></article>)}</div></div>}
  {view==="account"&&<div className="page account"><div className="accountHero"><div className="bigAvatar">{user.name.slice(0,2)}</div><div><p>{t("TÀI KHOẢN ĐẠI LÝ","經銷商帳戶")}</p><h1>{user.name}</h1><span>{user.username} · {tierLabel}</span></div><button onClick={()=>setUser(null)}>{t("Đăng xuất","登出")}</button></div><div className="accountGrid"><section><h2>{t("Đơn hàng gần đây","最近訂單")}</h2><div className="order"><div><b>#TD-260812-08</b><small>12/08/2026</small></div><span className="pending">{t("Chờ xác nhận","等待確認")}</span><strong>4.860.000 ₫</strong><button onClick={()=>{add(1,100);setView("cart")}}>↻ {t("Đặt lại","再次訂購")}</button></div></section><aside><h2>{t("Cấp khách hàng","客戶等級")}</h2><p><b>{tierLabel}</b></p><p>{t("Bảng giá do Tân Đông quản lý.","價格表由新東後台管理。")}</p><hr/><p>⌖ {user.address}</p></aside></div></div>}
  </>}
  <nav className="bottomNav">{[["⌂","home","Trang chủ","首頁"],["▦","products","Sản phẩm","產品"],["＋","cart","Đặt hàng","訂貨"],["▶","videos","Video","影片"],["●","account","Của tôi","我的"]].map(n=><button key={n[1]} className={view===n[1]?"active":""} onClick={()=>{setAdmin(false);setView(n[1])}}><span>{n[0]}{n[1]==="cart"&&cartItems.length?<i>{cartItems.length}</i>:null}</span><small>{t(n[2],n[3])}</small></button>)}</nav>
  {selected&&<ProductModal p={selected} n={qty[selected.id]||1} setN={n=>changeQty(selected.id,n)} pc={percent(selected,qty[selected.id]||1)} unit={price(selected,qty[selected.id]||1)} tier={tierLabel} lang={lang} t={t} close={()=>setSelected(null)} add={()=>{add(selected.id,qty[selected.id]||1);setSelected(null)}}/>}{toast&&<div className="toast">✓ {toast}</div>}</main>;
}

function Cart({items,total,cart,setCart,price,percent,lang,user,t,goProducts,submit}:{items:(Product&{quantity:number})[];total:number;cart:Record<number,number>;setCart:React.Dispatch<React.SetStateAction<Record<number,number>>>;price:(p:Product,n:number)=>number;percent:(p:Product,n:number)=>number;lang:"vi"|"zh";user:Customer;t:(a:string,b:string)=>string;goProducts:()=>void;submit:()=>void}){
 return <div className="page narrow"><div className="pageTitle"><p className="eyebrow">{t("ĐƠN HÀNG MỚI","新訂單")}</p><h1>{t("Kiểm tra đơn hàng","確認訂單")}</h1></div>{items.length?<><div className="cartList">{items.map(p=><div className="cartItem" key={p.id}><img src={p.image} alt=""/><div><b>{lang==="vi"?p.name:p.zh}</b><small>{p.code} · <del>{fmt(p.base)}</del> <strong>{fmt(price(p,p.quantity))}</strong> · {percent(p,p.quantity)}%</small></div><div className="stepper"><button onClick={()=>setCart({...cart,[p.id]:Math.max(1,p.quantity-1)})}>−</button><input type="number" value={p.quantity} onChange={e=>setCart({...cart,[p.id]:Math.max(1,Number(e.target.value))})}/><button onClick={()=>setCart({...cart,[p.id]:p.quantity+1})}>＋</button></div><strong>{fmt(price(p,p.quantity)*p.quantity)}</strong></div>)}</div><div className="summary"><div><span>{t("Tạm tính","小計")}</span><b>{fmt(total)}</b></div><div><span>{t("Giao đến","送貨地址")}</span><p>{user.address}</p></div><button className="primary" onClick={submit}>{t("Gửi đơn cho Tân Đông xác nhận","送出訂單，等待新東確認")} →</button><small>ⓘ {t("Giá theo cấp khách hàng và số lượng hiện tại.","價格依目前客戶等級與訂購數量計算。")}</small></div></>:<div className="empty"><span>▤</span><h2>{t("Đơn hàng đang trống","訂單目前是空的")}</h2><button className="primary" onClick={goProducts}>{t("Chọn sản phẩm","選擇產品")}</button></div>}</div>
}

function ProductModal({p,n,setN,pc,unit,tier,lang,t,close,add}:{p:Product;n:number;setN:(n:number)=>void;pc:number;unit:number;tier:string;lang:"vi"|"zh";t:(a:string,b:string)=>string;close:()=>void;add:()=>void}){
 return <div className="modalBackdrop" onClick={close}><section className="modal priceModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="detailVisual"><img src={p.image} alt=""/></div><p className="eyebrow">{p.code} · {lang==="vi"?p.category:p.categoryZh}</p><h2>{lang==="vi"?p.name:p.zh}</h2><p>{p.spec}</p><div className="modalPricing"><div><span>{t("Giá niêm yết","牌價")}</span><del>{fmt(p.base)}</del></div><div className="activePrice"><span>{t("Đơn giá hiện tại","目前單價")}</span><b>{fmt(unit)}</b></div><small>{tier} · {t("Thanh toán","支付牌價的")} {pc}%</small></div><div className="qtyPicker"><label>{t("Số lượng","訂購數量")}<div><button onClick={()=>setN(Math.max(1,n-1))}>−</button><input type="number" min="1" value={n} onChange={e=>setN(Math.max(1,Number(e.target.value)))}/><button onClick={()=>setN(n+1)}>＋</button></div></label><div className="quickQty"><button onClick={()=>setN(1)}>1 pcs</button><button onClick={()=>setN(p.packQty)}>{t("1 thùng","1箱")} ({p.packQty})</button><button onClick={()=>setN(p.packQty*10)}>{t("10 thùng","10箱")} ({p.packQty*10})</button></div></div><div className="tierSteps"><span className={n<p.packQty?"active":""}>1 pcs</span><i>→</i><span className={n>=p.packQty&&n<p.packQty*10?"active":""}>{t("1 thùng","1箱")}</span><i>→</i><span className={n>=p.packQty*10?"active":""}>{t("10 thùng","10箱")}</span></div><dl><div><dt>{t("Quy cách đóng gói","包裝數量")}</dt><dd>{lang==="vi"?p.pack:p.packZh}</dd></div><div><dt>{t("Thành tiền","總額")}</dt><dd>{fmt(unit*n)}</dd></div></dl><button className="primary" onClick={add}>{t("Thêm vào đơn hàng","加入訂單")} <span>＋</span></button></section></div>
}

function Admin({customers,setCustomers,rules,setRules,products,setProducts,close,t}:{customers:Customer[];setCustomers:React.Dispatch<React.SetStateAction<Customer[]>>;rules:Record<Tier,Rule>;setRules:React.Dispatch<React.SetStateAction<Record<Tier,Rule>>>;products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;close:()=>void;t:(a:string,b:string)=>string}){
 const [tab,setTab]=useState("products");const [draft,setDraft]=useState(rules);const [saved,setSaved]=useState(false);const [productSearch,setProductSearch]=useState("");
 const nav=[["▤","orders",t("Đơn hàng","訂單管理")],["●","customers",t("Khách hàng","客戶管理")],["♟","tiers",t("Cấp khách hàng","客戶等級")],["％","discounts",t("Chiết khấu số lượng","數量折扣")],["▦","products",t("Sản phẩm","產品管理")]];
 const title:Record<string,string>={orders:t("Quản lý đơn hàng","訂單管理"),customers:t("Phân loại khách hàng","客戶分類管理"),tiers:t("Ba cấp khách hàng","三級客戶設定"),discounts:t("Chiết khấu theo số lượng","數量階梯折扣"),products:t("Danh mục & sản phẩm","分類與產品管理")};
 const update=(tier:Tier,key:keyof Rule,v:number)=>setDraft(d=>({...d,[tier]:{...d[tier],[key]:Math.min(100,Math.max(1,v||1))}}));
 const updateBase=(code:string,value:number)=>setProducts(list=>list.map(p=>p.code===code?{...p,base:Math.max(0,value||0)}:p));
 const visibleProducts=products.filter(p=>`${p.code} ${p.category} ${p.categoryZh}`.toLowerCase().includes(productSearch.toLowerCase()));
 return <div className="admin"><aside><div className="logo"><span>TĐ</span><b>TÂN ĐÔNG<small>ADMIN</small></b></div><p>{t("QUẢN LÝ HỆ THỐNG","系統管理")}</p>{nav.map(x=><button className={tab===x[1]?"active":""} onClick={()=>setTab(x[1])} key={x[1]}><i>{x[0]}</i>{x[2]}</button>)}<button className="back" onClick={close}>← {t("Về trang đại lý","返回經銷商頁")}</button></aside><section className="adminMain"><div className="adminHead"><div><p>TÂN ĐÔNG PRO</p><h1>{title[tab]}</h1></div>{tab==="discounts"&&<button onClick={()=>{setRules(draft);setSaved(true);setTimeout(()=>setSaved(false),1600)}}>{saved?t("✓ Đã áp dụng","✓ 已套用"):t("Lưu & áp dụng","儲存並套用")}</button>}</div>
 {(tab==="tiers"||tab==="discounts")&&<div className="adminIntro"><b>{tab==="tiers"?t("Giá bắt đầu từ giá niêm yết và cấp username.","所有售價皆從牌價及Username客戶等級開始計算。") : t("Tỷ lệ 90% nghĩa là khách trả 90% giá niêm yết.","90%代表客戶支付牌價的90%，即九折。")}</b><span>{t("Lưu xong sẽ áp dụng ngay trên giao diện đặt hàng.","儲存後會立即反映在客戶訂貨介面。")}</span></div>}
 {tab==="tiers"&&<div className="tierAdminGrid">{(["large","medium","small"] as Tier[]).map((tier,i)=><article key={tier}><span className={`tierIcon tier${i}`}>{i+1}</span><div><p>{tierInfo[tier].code}</p><h2>{t(tierInfo[tier].vi,tierInfo[tier].zh)}</h2><small>{customers.filter(c=>c.tier===tier).length} {t("tài khoản","個帳號")}</small></div><ul><li>1 pcs <b>{draft[tier].single}%</b></li><li>{t("1 thùng","1箱")} <b>{draft[tier].carton}%</b></li><li>{t("10 thùng","10箱")} <b>{draft[tier].tenCartons}%</b></li></ul></article>)}</div>}
 {tab==="discounts"&&<div className="discountEditor"><div className="discountHeader"><span>{t("Cấp khách hàng","客戶等級")}</span><span>1 pcs</span><span>{t("1 thùng","1箱")}</span><span>{t("10 thùng","10箱")}</span></div>{(["large","medium","small"] as Tier[]).map(tier=><div className="discountRow" key={tier}><span><b>{t(tierInfo[tier].vi,tierInfo[tier].zh)}</b><small>{tierInfo[tier].code}</small></span>{(["single","carton","tenCartons"] as (keyof Rule)[]).map(key=><label key={key}><input type="number" min="1" max="100" value={draft[tier][key]} onChange={e=>update(tier,key,Number(e.target.value))}/><i>%</i></label>)}</div>)}<div className="formulaBox"><b>{t("Công thức giá","價格公式")}</b><code>{t("Giá bán = Giá niêm yết × Tỷ lệ theo cấp & số lượng","售價＝牌價 × 客戶等級與數量百分比")}</code><small>{t("Ngưỡng tự tính theo quy cách đóng gói từng sản phẩm.","數量門檻依每項產品包裝數量自動換算。")}</small></div></div>}
 {tab==="customers"&&<div className="adminTable"><div className="tableTools"><b>{t("Username & cấp khách hàng","Username與客戶等級")}</b></div><div className="customerHeader"><span>USERNAME / {t("KHÁCH HÀNG","客戶")}</span><span>{t("CẤP HIỆN TẠI","目前等級")}</span><span>{t("QUYỀN XEM GIÁ","價格權限")}</span></div>{customers.map(c=><div className="customerRow" key={c.username}><span><b>{c.name}</b><small>@{c.username}</small></span><select value={c.tier} onChange={e=>setCustomers(list=>list.map(x=>x.username===c.username?{...x,tier:e.target.value as Tier}:x))}><option value="large">{t("Đại lý lớn / Đại bàn","大盤客戶")}</option><option value="medium">{t("Đại lý vừa / Trung bàn","中盤客戶")}</option><option value="small">{t("Cửa hàng / Tiểu bàn","小盤客戶")}</option></select><span className="permission">✓ {t("Chỉ giá của cấp này","僅顯示此等級價格")}</span></div>)}</div>}
 {tab==="products"&&<div className="productAdminStack"><div className="adminIntro"><b>{t("Giá niêm yết được quản lý theo mã sản phẩm.","牌價依產品編號管理。")}</b><span>{t("Thay đổi tại đây sẽ cập nhật ngay giá và chiết khấu trên giao diện đại lý.","在此修改後，經銷商介面的牌價與折扣價會立即更新。")}</span></div><div className="adminTable"><div className="tableTools"><div><b>{t("4 danh mục theo website cũ","舊官網圈選的4個分類")}</b><small>{products.length} {t("sản phẩm đã nhập","項產品已匯入")}</small></div><span className="countPill">4 {t("danh mục","個分類")}</span></div>{catalogueGroups.map((g,i)=><button className="categoryAdminRow categorySummary" key={g.en} onClick={()=>setProductSearch(g.vi)}><span>{i+1}</span><b><em>{g.en}</em>{t(g.vi,g.zh)}</b><small>{products.filter(p=>p.category===g.vi).length} {t("sản phẩm","項產品")}</small><strong>→</strong></button>)}</div><div className="adminTable productPriceTable"><div className="tableTools"><div><b>{t("Bảng giá niêm yết theo mã sản phẩm","依產品編號設定牌價")}</b><small>{t("Đơn vị: VND / pcs","單位：VND／件")}</small></div><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder={t("Tìm mã sản phẩm...","搜尋產品編號…")}/></div><div className="productPriceHeader"><span>{t("HÌNH / MÃ SẢN PHẨM","圖片／產品編號")}</span><span>{t("DANH MỤC","分類")}</span><span>{t("GIÁ NIÊM YẾT","牌價")}</span><span>{t("GIÁ ĐẠI LÝ LỚN","大盤單件價")}</span></div>{visibleProducts.map(p=><div className="productPriceRow" key={p.id}><span><img src={p.image} alt=""/><b>{p.code}</b></span><span><small>{p.categoryEn}</small>{t(p.category,p.categoryZh)}</span><label><input type="number" min="0" step="1000" value={p.base} onChange={e=>updateBase(p.code,Number(e.target.value))}/><i>₫</i></label><strong>{fmt(p.base*rules.large.single/100)}</strong></div>)}</div></div>}
 {tab==="orders"&&<div className="adminTable"><div className="tableTools"><b>{t("Đơn hàng gần đây","最近訂單")}</b></div>{customers.concat(customers).slice(0,5).map((c,i)=><div className="tr" key={i}><span><b>#TD-260812-0{8-i}</b><small>{c.name} · {t(tierInfo[c.tier].vi,tierInfo[c.tier].zh)}</small></span><span>12/08/2026</span><span><i className="status">{t("Chờ xác nhận","等待確認")}</i></span><span><b>{[4860000,7325000,2190000,8920000,3450000][i].toLocaleString("vi-VN")} ₫</b></span></div>)}</div>}
 <div className="adminNote">ⓘ {t("Bản mẫu quản trị — dữ liệu mô phỏng, chưa kết nối ERP.","管理後台原型——目前為模擬資料，尚未連接ERP。")}</div></section></div>
}
